name: Build-win

on:
  push:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build app on Windows
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          npm install
          npm run electron:windows

      - name: Package artifacts
        run: |
          mkdir artifact-setup
          mv release/*-setup.exe* artifact-setup/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/*-setup.exe*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true


