name: Build/release

on:
  push

jobs:
  release_win:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12
        
      - name: Build app on Windows
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        if: runner.os == 'Windows'
        run: |
          npm install
          npm run electron:windows
      
      - name: Build app on Linux
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        if: runner.os == 'Linux'
        run: |
          npm install
          npm run electron:linux
          
      - name: Build app on MacOS
        if: runner.os == 'macOS'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          npm install
          npm run electron:mac

      - name: Package artifacts
        run: |
          mkdir artifact-setup
          mv release/*-setup.exe artifact-setup/
          
      - uses: actions/upload-artifact@master
        name: Upload installer
        with:
          name: Installer
          path: artifact-setup
            
