name: Build/release

on:
  push

jobs:
  release_win:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12
          
      - name: Install Node dependencies
        run: npm install

      - name: Build app
        shell: pwsh
        run: |
          if($env:RUNNER_OS -eq "Linux") {
            npm run electron:linux
          }
          elseif($env:RUNNER_OS -eq "Windows") {
            npm run electron:windows
          }
          elseif($env:RUNNER_OS -eq "macOS") {
            npm run electron:mac
          }
          
      - name: list files
        run: |
          cd release
          ls

      - name: Release app
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            release/*-setup.exe
            
